[project]

name = "wtftw"
version = "0.0.2"
authors = ["Simon Wollwage"]

[dependencies.xlib]
git = "https://github.com/Kintaro/rust-xlib.git"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[lib]
name = "wtftw"

[[bin]]
name = "wtftw"
