[project]

name = "wtftw"
version = "0.2.0"
authors = ["Simon Wollwage"]

[dependencies.wtftw_core]
path = "core"

[dependencies.wtftw_xlib]
path = "xlib"

[target.x86_64-unknown-linux-gnu.wtftw]
rustc-flags = "-C prefer-dynamic"

[[bin]]
name = "wtftw"
path = "src/wtftw.rs"
