[project]

name = "wtftw"
version = "0.1.0"
authors = ["Simon Wollwage"]

[dependencies.wtftw_core]
git = "https://github.com/Kintaro/wtftw-core.git"

[dependencies.wtftw_xlib]
git = "https://github.com/Kintaro/wtftw-xlib.git"

[target.x86_64-unknown-linux-gnu.wtftw]
rustc-flags = "-C prefer-dynamic"

[[bin]]
name = "wtftw"
path = "src/wtftw.rs"
