[project]

name = "wtftw"
version = "0.0.1"
authors = ["Simon Wollwage"]

[dependencies.xlib]
git = "https://github.com/servo/rust-xlib.git"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[[bin]]
name = "wtftw"
plugin = true
