[project]

name = "wtftw_core"
version = "0.2.0"
authors = ["Simon Wollwage"]

[lib]
name = "wtftw_core"
path = "src/wtftw.rs"
crate-type = ["rlib"]

[target.x86_64-unknown-linux-gnu.wtftw]
rustc-flags = "-C prefer-dynamic"
