[project]

name = "wtftw_xlib"
version = "0.2.0"
authors = ["Simon Wollwage"]

[dependencies.xlib]
#git = "https://github.com/Kintaro/rust-xlib.git"
path = "/home/wollwage/code/rust/rust-xlib"
#branch = "sizehint"

[dependencies.xinerama]
#git = "https://github.com/Kintaro/rust-xinerama.git"
path = "/home/wollwage/code/rust/rust-xinerama"

[dependencies.wtftw_core]
path = "../core"

[lib]
name = "wtftw_xlib"
path = "src/xlib_window_system.rs"
crate-type = ["rlib"]

[target.x86_64-unknown-linux-gnu.wtftw]
rustc-flags = "-C prefer-dynamic"
